# Generated by Django 4.2.11 on 2024-04-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holid_season', models.SlugField(choices=[(0, 'Spring'), (1, 'Summer'), (2, 'Autumn'), (3, 'Winter')], default=0)),
                ('sites', models.CharField(max_length=200)),
                ('holid_length', models.CharField(max_length=200)),
                ('restaurants', models.CharField(max_length=200)),
                ('to_avoid', models.CharField(max_length=200)),
                ('cost_expected', models.CharField(max_length=200)),
                ('bag_recommendation', models.CharField(max_length=200)),
                ('over_view', models.TextField()),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_recommendation', to='blog.post')),
            ],
        ),
    ]
