# Generated by Django 4.2.11 on 2024-05-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='holiday_season',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
