# Generated by Django 4.2.11 on 2024-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_holiday_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='holiday_season',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
