# Generated by Django 4.2.11 on 2024-04-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='holid_length',
            new_name='holiday_length',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='holid_season',
            new_name='holiday_season',
        ),
    ]
