# Generated by Django 4.2.11 on 2024-04-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_holid_length_recommendation_holiday_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='holiday_season',
            field=models.PositiveIntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Autumn'), (4, 'Winter')], default=1),
        ),
    ]
